services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    pid: host
    network_mode: host

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    environment:
      - GLANCES_OPT=-w

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
