- Netzwerk:
    - AdGuard:
        href: http://192.168.178.36
        description: DNS & Werbeblocker
        icon: adguard-home.png

- Medien:
    - Jellyfin:
        href: http://192.168.178.36:8096
        description: Filme & Serien
        icon: jellyfin.png

- Verwaltung:
    - Portainer:
        href: https://192.168.178.36:9443
        description: Docker-Verwaltung
        icon: portainer.png

- Smart Home:
    - Home Assistant:
        href: http://192.168.178.36:8123
        description: Smart-Home-Zentrale
        icon: home-assistant.png
