---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Wintermute
description: Homeserver Dashboard
layout:
  Medien:
  Netzwerk:
  Verwaltung:
background:
  image: https://images.unsplash.com/photo-1782679226951-2e916ce69988?q=80&w=794&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  blur: sm
  saturate: 50
  brightness: 60
  opacity: 80
