---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Wintermute
description: Homeserver Dashboard

layout:
  Medien:
  Netzwerk:
  Verwaltung:
