---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/
- resources:
    cpu: true
    memory: true
    disk:
      - /
      - /mnt/media
      - /mnt/nas6tb
    network: ens18
- glances:
    url: http://192.168.178.36:61208
    version: 4
    cpu: false
    mem: false
    cputemp: true
    cpuSensorLabel: "Package id"
    uptime: true
- datetime:
    locale: de
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
