services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri

    ports:
      - "8096:8096"

    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/media:/media
