services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=ivpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_HOSTNAMES=${IVPN_SERVER_HOSTNAME}
      - FIREWALL_OUTBOUND_SUBNETS=192.168.178.0/24   # LAN-Zugriff auf die UIs erlauben
    ports:
      - 6789:6789    # NZBGet
      - 7878:7878    # Radarr
      - 8989:8989    # Sonarr
      - 9696:9696    # Prowlarr
      - 5055:5055    # Jellyseerr
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/nas6tb/media-automation/nzbget/config:/config
      - /mnt/media/downloads:/downloads
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/nas6tb/media-automation/radarr/config:/config
      - /mnt/media:/media
      - /mnt/media/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/nas6tb/media-automation/sonarr/config:/config
      - /mnt/media:/media
      - /mnt/media/downloads:/downloads
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/nas6tb/media-automation/prowlarr/config:/config
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /mnt/nas6tb/media-automation/jellyseerr/config:/app/config
    restart: unless-stopped

