services:
  app:
    image: ghcr.io/danielbrendel/hortusfox-web:latest
    container_name: hortusfox
    restart: unless-stopped
    ports:
      - "8060:80"
    volumes:
      - /mnt/nas6tb/hortusfox/images:/var/www/html/public/img
      - /mnt/nas6tb/hortusfox/logs:/var/www/html/app/logs
      - /mnt/nas6tb/hortusfox/backup:/var/www/html/public/backup
      - /mnt/nas6tb/hortusfox/themes:/var/www/html/public/themes
      - /mnt/nas6tb/hortusfox/migrate:/var/www/html/app/migrations
    environment:
      APP_ADMIN_EMAIL: ${APP_ADMIN_EMAIL}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      APP_TIMEZONE: "Europe/Berlin"
      DB_HOST: hortusfox-db
      DB_PORT: 3306
      DB_DATABASE: hortusfox
      DB_USERNAME: hortusfox-user
      DB_PASSWORD: ${MARIADB_PASSWORD}
      DB_CHARSET: "utf8mb4"
    depends_on:
      - hortusfox-db

  hortusfox-db:
    image: mariadb:latest
    container_name: hortusfox-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: hortusfox
      MARIADB_USER: hortusfox-user
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - /mnt/nas6tb/hortusfox/mysql_data:/var/lib/mysql

